kind: pipeline
type: docker
name: 后端服务

# 定义全局环境变量
environment:
  - N_USER:
    from_secret: n_user
  - N_HOST:
    from_secret: n_ip
  - N_PATH: /volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script

volumes:
  - name: maven-cache
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/maven-cache
  - name: run-script
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script

steps:
  - name: 部署项目
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: ssh_ip
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pw
      port: 22
      command_timeout: 2m
      script:
        - echo $N_USER
        - cd /www/wwwroot/pageplug/
        - pwd
        - mkdir -p server
        - rm -rf ./server/*
        - scp -r $N_USER@$N_HOST:$N_PATH/* /www/wwwroot/pageplug/server
        - cd server
        - ls -al
trigger:
  branch:
    - main