kind: pipeline
type: docker
name: 后端服务

volumes:
  - name: maven-cache
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/maven-cache
  - name: run-script
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script

steps:
  - name: 部署项目
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: ssh_ip
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pw
      port: 22
      command_timeout: 2m
      envs:
        - n_user
        - n_ip
      script:
        - cd /www/wwwroot/pageplug/
        - pwd
        - mkdir -p server
        - rm -rf ./server/*
        - echo "$NAS_USER@$NAS_HOST:/volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script/"
        - scp -r $NAS_USER@$NAS_HOST:/volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script/pageplug/* /www/wwwroot/pageplug/server
        - cd server
        - ls -al
trigger:
  branch:
    - main