kind: pipeline
type: docker
name: 后端服务

volumes:
  - name: maven-cache
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/maven-cache
  - name: run-script
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script
- name: 清空server
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: ssh_ip
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_pw
      port: 22
      command_timeout: 2m
      script:
        - cd /www/wwwroot/pageplug/
        - pwd
        - mkdir -p server
        - rm -rf ./server/*
trigger:
  branch:
    - main

---
kind: pipeline
type: ssh
name: 后端部署
clone:
  disable: true
server:
  host:
    from_secret: n_ip
  user:
    from_secret: n_user
  password:
    from_secret: n_pw

steps:
  - name: 部署项目
    environment:
      N_USER:
        from_secret: n_user
      N_IP:
        from_secret: n_ip
      N_PW:
        from_secret: n_pw
      N_PATH: /volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script
    commands:
      - cd $N_PATH/pageplug/
      - pwd
      - scp -r $N_USER@$N_IP:$N_PATH/pageplug/* /www/wwwroot/pageplug/server
